/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.toystore.form.store;

import com.toystore.dao.store.CategoryDAO;
import com.toystore.dao.store.OrderDAO;
import com.toystore.dao.store.OrderDetailDAO;
import com.toystore.dao.store.productDAO;
import com.toystore.model.StatusType;
import com.toystore.model.store.Category;
import com.toystore.model.store.Order;
import com.toystore.model.store.OrderDetail;
import com.toystore.model.store.product;
import com.toystore.swing.ButtonRendererEditor;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import org.slf4j.helpers.MessageFormatter;

/**
 *
 * @author Asus
 */
public class OrderView extends javax.swing.JPanel {

    public int row = 0;

    /**
     * Creates new form categoryView
     */
    public OrderView() {
        initComponents();

        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        tableCategory.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        orderList = orderDAO.findAll();
        fillTable(orderList);
    }
    OrderDAO orderDAO = new OrderDAO();
    List<Order> orderList = new ArrayList<>();
    List<OrderDetail> orderDetails = new ArrayList<>();
    Order OrderJustNow = new Order();

    productDAO productDao = new productDAO();
    public double totalAmountSP = 0;
    DecimalFormat df = new DecimalFormat("#,###,###,###");
    OrderDetailDAO orderDetailDAO = new OrderDetailDAO();

    public void fillToTableHoaDon(List<OrderDetail> details) {
        String row[] = {"Tên sản phẩm", "Giá", "Số lượng", "Tổng Tiền"};
        DefaultTableModel modelTbl = new DefaultTableModel(row, 0);
        modelTbl.setRowCount(0);
        totalAmountSP = 0;
        for (OrderDetail detail : details) {
            product sp = productDao.findById(detail.productId);  // Lấy thông tin sản phẩm
            double totalPrice = detail.quantity * detail.unitPrice;
            modelTbl.addRow(new Object[]{
                sp.getName(),
                df.format(detail.unitPrice) + " VND",
                detail.quantity,
                df.format(totalPrice) + " VND"
            });
            totalAmountSP += totalPrice;
        }
//        txtTienSP.setText(df.format(totalAmountSP));
        tblOrderDetail.setModel(modelTbl);
        if (tblOrderDetail.getColumnModel().getColumnCount() > 2) {
//            tblOrderDetail.getColumnModel().getColumn(2).setCellEditor(new Menu.SpinnerEditor());
//            tblOrderDetail.getColumnModel().getColumn(2).setCellRenderer(new Menu.SpinnerRenderer());
            tblOrderDetail.setRowHeight(25);
//            tblHoaDon.setRow
        }
    }

    void fillTable(List<Order> orderList) {
        String row[] = {"Mã SP", "Tên Mã nhân ", "Giá SP", "Ngày thanh toán", "loại thanh toán", "Bar CODE", "___"};
        DefaultTableModel model = new DefaultTableModel(row, 0);
        model.setRowCount(0);
//        model.setModel(model);
        for (Order order : orderList) {
            model.addRow(new Object[]{order.getOrderId(), order.getAccountId(),
                order.getTotalAmount(), order.getOrderDate(),
                order.getPaymentMethodId(), "NULL"});
        }
//        table.getColumnModel().getColumn(4).setCellRenderer(new ButtonRendererEditor
//        table.getColumnModel().getColumn(4).setCellEditor(new ButtonRendererEditor());
        table.setModel(model);
    }

    public void fillOrderDetail(List<OrderDetail> orderDetailList) {
        String row[] = {};
        DefaultTableModel model = new DefaultTableModel();
        model.setRowCount(0);
        for (OrderDetail orderDetail : orderDetailList) {
            model.addRow(
                    new Object[]{
                        orderDetail.getOrderDetailId(),
                        orderDetail.getProductId()
                    }
            );
        }
        tblOrderDetail.setModel(model);
    }

    public void selectFillHDC(int indexHD1) {
        OrderJustNow = orderList.get(indexHD1);
        orderDetails = orderDetailDAO.findByOrderID(String.valueOf(OrderJustNow.getOrderId()));
        fillToTableHoaDon(orderDetails);
    }

    public void setFrom() {
        txtOrderID.setText(String.valueOf(row));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new com.toystore.swing.PanelBorder();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrderDetail = new javax.swing.JTable();
        tableCategory = new javax.swing.JScrollPane();
        table = new com.toystore.swing.Table();
        jLabel1 = new javax.swing.JLabel();
        txtOrderID = new javax.swing.JTextField();

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        tblOrderDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblOrderDetail);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        tableCategory.setViewportView(table);

        jLabel1.setText("MÃ HÓA ĐƠN");

        txtOrderID.setText("O1");
        txtOrderID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tableCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(txtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tableCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        row = table.getSelectedRow();
        System.out.println("lỏ" + row);
        setFrom();
        selectFillHDC(row);

    }//GEN-LAST:event_tableMouseClicked

    private void txtOrderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toystore.swing.PanelBorder panelBorder1;
    private com.toystore.swing.Table table;
    private javax.swing.JScrollPane tableCategory;
    private javax.swing.JTable tblOrderDetail;
    private javax.swing.JTextField txtOrderID;
    // End of variables declaration//GEN-END:variables
}
