/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.toystore.form;
    
    import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
/**
 *
 * @author Asus
 */
public class AddProductForm extends javax.swing.JFrame {

    /**
     * Creates new form AddProductForm
     */
//    public AddProductForm() {
//        initComponents1();
//    }
//    


//public class AddProductForm extends JFrame {
    private JTextField txtMaSP;
    private JTextField txtTenSP;
    private JTextField txtMaLoai;
    private JTextField txtMoTa;
    private JTextField txtSoLuong;

    private JButton btnThem;

    private static final String DB_URL = "jdbc:sqlserver://localhost:1433;databaseName=Tore";
    private static final String USER = "sa";
    private static final String PASSWORD = "123";
      String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Tore;user=sa;password=123;encrypt=true;trustServerCertificate=true;";

    public AddProductForm() {
        setTitle("Thêm Sản Phẩm");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        initComponents1();
        addEventListeners();
    }

    private void initComponents1() {
        txtMaSP = new JTextField(20);
        txtTenSP = new JTextField(20);
        txtMaLoai = new JTextField(20);
        txtMoTa = new JTextField(20);
        txtSoLuong = new JTextField(20);

        btnThem = new JButton("Thêm");

        setLayout(new GridLayout(6, 2));

        add(new JLabel("Mã SP:"));
        add(txtMaSP);
        add(new JLabel("Tên SP:"));
        add(txtTenSP);
        add(new JLabel("Mã Loại:"));
        add(txtMaLoai);
        add(new JLabel("Mô Tả:"));
        add(txtMoTa);
        add(new JLabel("Số Lượng:"));
        add(txtSoLuong);

        add(new JLabel()); // Placeholder for layout
        add(btnThem);
    }

    private void addEventListeners() {
        btnThem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                addProductToDatabase();
            }
        });
    }

    private void addProductToDatabase() {
        try {
//            Connection connection = DriverManager.getConnection(DB_URL, USER, PASSWORD);
              Connection connection = DriverManager.getConnection(connectionUrl);

            String sql = "INSERT INTO sanpham (MaSP, TenSP, MaLoai, MoTa, Soluong) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement preparedStatement = connection.prepareStatement(sql);

            preparedStatement.setString(1, txtMaSP.getText());
            preparedStatement.setString(2, txtTenSP.getText());
            preparedStatement.setString(3, txtMaLoai.getText());
            preparedStatement.setString(4, txtMoTa.getText());
            preparedStatement.setInt(5, Integer.parseInt(txtSoLuong.getText()));

            preparedStatement.executeUpdate();

            JOptionPane.showMessageDialog(this, "Sản phẩm đã được thêm vào cơ sở dữ liệu!");

            // Đóng kết nối
            preparedStatement.close();
            connection.close();
        } catch (SQLException | NumberFormatException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm sản phẩm!");
        }
    }

//    public static void main(String[] args) {
//        SwingUtilities.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new AddProductForm().setVisible(true);
//            }
//        });
//    }
//}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProductForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProductForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
